#!/bin/sh
set -e
DIR="$(dirname "$0")"
export DIET_FOODS_DIR="$DIR/foods"
cargo build --quiet --manifest-path "$DIR/diet-tracker/Cargo.toml"
if [ -x "$DIR/diet-tracker/target/release/diet-tracker" ]; then
  BIN="$DIR/diet-tracker/target/release/diet-tracker"
else
  BIN="$DIR/diet-tracker/target/debug/diet-tracker"
fi
exec "$BIN" \
  --foods-dir "$DIR/foods" \
  --log-dir "$DIR/log" \
  "$@"
