title = "Turkey Chili 98% Lean"
servings = 5

[[ingredients]]
name = "Turkey 98%"
quantity = "2 lbs"
protein_g = 192
fiber_g = 0
calories = 960

[[ingredients]]
name = "Oil"
quantity = "42g"
protein_g = 0
fiber_g = 0
calories = 360

[[ingredients]]
name = "Petite diced tomato"
quantity = "2 cans"
protein_g = 6
fiber_g = 8
calories = 140

[[ingredients]]
name = "Onion"
quantity = "10oz"
protein_g = 3
fiber_g = 5
calories = 115

[[ingredients]]
name = "Black beans"
quantity = "1 can"
protein_g = 24
fiber_g = 18
calories = 390

[[ingredients]]
name = "Kidney beans"
quantity = "1 can"
protein_g = 24
fiber_g = 17
calories = 380

[[ingredients]]
name = "Bone broth"
quantity = "140g"
protein_g = 5
fiber_g = 0
calories = 25
